apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
      - name: mvn test
        uses: docker://maven:3.9.5-eclipse-temurin-11
        shell: sh
        run: |
          mvn test
